# Generated by Django 3.2.6 on 2023-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='description',
            new_name='description_raw_data',
        ),
        migrations.AddField(
            model_name='episode',
            name='readable_description',
            field=models.TextField(default=['datetime', 'timezone']),
            preserve_default=False,
        ),
    ]
