# Generated by Django 3.2.6 on 2023-04-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0003_remove_episode_readable_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="description_raw_data",
            new_name="description",
        ),
    ]
