# Generated by Django 3.2.6 on 2023-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_podcast_podcast_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='feed_href',
            field=models.URLField(unique=True),
        ),
    ]
