# Generated by Django 3.2.6 on 2023-04-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_alter_podcast_feed_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='image',
        ),
    ]
