# Generated by Django 3.2.6 on 2023-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_remove_episode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.URLField(default='image.jpg'),
            preserve_default=False,
        ),
    ]
