# Generated by Django 3.2.6 on 2023-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0012_episode_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="host",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
