# Generated by Django 3.2.6 on 2023-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_podcast_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='host',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcast_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
