# Generated by Django 4.1 on 2023-07-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0014_auto_20230418_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="guid",
            field=models.CharField(max_length=100),
        ),
    ]
