# Generated by Django 4.1 on 2023-08-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0015_alter_episode_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="guid",
            field=models.CharField(max_length=200),
        ),
    ]
