# Generated by Django 4.1 on 2023-08-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0018_channel_youtubeepisode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubeepisode",
            name="podcast_name",
        ),
        migrations.AddField(
            model_name="channel",
            name="youtube_url",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="youtubeepisode",
            name="channel_name",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="podcasts.channel",
            ),
            preserve_default=False,
        ),
    ]
