# Generated by Django 4.1 on 2023-08-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0019_remove_youtubeepisode_podcast_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="feed_href",
            field=models.URLField(),
        ),
    ]
