# Generated by Django 4.1 on 2023-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0020_alter_channel_feed_href"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_twitter",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="podcast_twitter",
            field=models.URLField(null=True, unique=True),
        ),
    ]
