# Generated by Django 4.1 on 2023-08-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0021_channel_channel_twitter_podcast_podcast_twitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_twitter",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="podcast_image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="podcast_twitter",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
