# Generated by Django 4.1 on 2023-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0022_alter_channel_channel_twitter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="requires_filter",
            field=models.BooleanField(null=True),
        ),
    ]
