# Generated by Django 4.1 on 2023-08-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0023_podcast_requires_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="requires_filter",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
