# Generated by Django 4.1 on 2023-09-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0025_channel_requires_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="announced_to_twitter",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="episode",
            name="fetched_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="youtubeepisode",
            name="announced_to_twitter",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubeepisode",
            name="fetched_date",
            field=models.DateTimeField(null=True),
        ),
    ]
