# Generated by Django 4.1 on 2023-10-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0027_alter_channel_requires_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="requires_filter",
            field=models.BooleanField(null=True),
        ),
    ]
