name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

env:
  # Environmental Variables

  # Secrets
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}

  # Settings
  DJANGO_SETTINGS_MODULE: 'content_aggregator.settings.ci'


jobs:
  build:
    services:
      mysql:
        image: mysql:8.0
    env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest
